### PR TITLE
Time shift [WIP]

### PR DESCRIPTION
**Pull request by dapi**

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#22](https://github.com/zold-io/zold-score/issues/22) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#22](https://github.com/zold-io/zold-score/issues/22) is assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/74a7fb6a-77fe-41a0-9add-7896cfbd4a08); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@emilianodellacasa Looks like no work was done here by you since the PR was closed earlier :) Right?

**Comment by ypshenychka** [comment]
@dapi According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to

Please add appropriate description with link to an issue. Even if PR was closed, we should keep our documentation in a proper state.

**Comment by emilianodellacasa** [comment]
@ypshenychka Recently it seems the story of my life. :-) Confirmed

**Comment by ypshenychka** [comment]
@emilianodellacasa Something weird is happing :)

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
> @0crat quality bad ([here](https://github.com/zold-io/zold-score/issues/22#issuecomment-446511375))

@ypshenychka There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@041da5f8-f9e0-45ec-8176-7f0140d878bb, thread: AsyncProc-5
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.cost.funding.send_zold
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: groovy.lang.MissingMethodException: No signature of method: com.zerocracy.pmo.banks.Zold.pay() is applicable for argument types: (java.lang.String, com.zerocracy.cash.Cash$S, java.lang.String) values: [ypshenychka, $2.13, none]
Possible solutions: pay(java.lang.String, com.zerocracy.cash.Cash, java.lang.String, java.lang.String), any(), wait(), find(), dump(), grep()
org.codehaus.groovy.runtime.ScriptBytecodeAdapter[71] groovy.lang.MissingMethodException: No signature of method: com.zerocracy.pmo.banks.Zold.pay() is applicable for argument types: (java.lang.String, com.zerocracy.cash.Cash$S, java.lang.String) values: [ypshenychka, $2.13, none]
Possible solutions: pay(java.lang.String, com.zerocracy.cash.Cash, java.lang.String, java.lang.String), any(), wait(), find(), dump(), grep()
```

[0.39.6](https://github.com/zerocracy/farm): CID: [ff381bad-f6c9-40ce-a0ff-2a94be76c3eb](https://www.0crat.com/footprint/CAZPZR9FS/ff381bad-f6c9-40ce-a0ff-2a94be76c3eb), Type: "Send zold"

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request closed without merging**
