### PR TITLE
#2: Fast score mining (c++)

### PR DESCRIPTION
**Pull request by DronMDF**

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#3](https://github.com/zold-io/zold-score/issues/3) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#3](https://github.com/zold-io/zold-score/issues/3) is assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/d789d959-46b1-4adc-ab22-d75230e08dec); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
@DronMDF @yegor256 I don't see any major issue, excluding the fact that compiling this new module gives problems on AppVeyor. I don't know how we should address this problem, wether to solve it now, excluding AppVeyor or opening a specific issue for it, I am leaving the decision to the ARC

**Comment by DronMDF** [comment]
@emilianodellacasa I think about appveyor today...

**Comment by DronMDF** [comment]
This is a progress. :)
Try to fix tomorrow.

**Comment by DronMDF** [comment]
Strange.
The extension requires the ruby.h to be present.
This is explicitly checked in the generated Makefile.
```Makefile
ruby_headers = $(hdrdir)/ruby.h $(hdrdir)/ruby/backward.h $(hdrdir)/ruby/ruby.h $(hdrdir)/ruby/defines.h $(hdrdir)/ruby/missing.h $(hdrdir)/ruby/intern.h $(hdrdir)/ruby/st.h $(hdrdir)/ruby/subst.h $(arch_hdrdir)/ruby/config.h
```
But there is no ruby.h.
Where did I go wrong?

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@DronMDF there are some errors, see above

**Comment by DronMDF** [comment]
@yegor256 What is the version of the c++ compiler in the container?
I did not set the options for which the compiler swears. This is the default.

I see a problem with bundle:
```
GemWrappers: Can not wrap missing file: rake-compiler
```
What is it for?

ruby-dev installed?
We can install it over rultor.yml (for check)?

**Comment by yegor256** [comment]
@DronMDF ignore the warning from GemWrappers. Yes, ruby-dev is installed. This is the container: https://github.com/yegor256/rultor/blob/master/src/docker/Dockerfile

**Comment by yegor256** [comment]
@DronMDF you can run the build locally, inside Docker:

```
$ docker run -it --rm yegor256/rultor /bin/bash
```

Then, inside the container:

```
$ git clone https://github.com/zold-io/zold-score
$ cd zold-score
$ bundle install
$ rake
```

**Comment by DronMDF** [comment]
@yegor256  ok, i'll check it today.

**Comment by DronMDF** [comment]
@yegor256 I fix rultor build.

**Comment by yegor256** [comment]
@rultor merge

**Comment by DronMDF** [comment]
@yegor256 This is not me! :)

About appveyor. Makefile with rubyhdrdir generated from mkmf. This is standart ruby module.
Perhaps the ruby.h file is missing in the distribution.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#3](https://github.com/zold-io/zold-score/issues/3) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@DronMDF According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to

Please add appropriate description in your PR.

**Comment by ypshenychka** [comment]
@DronMDF According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct all your messages and code review comment by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@emilianodellacasa According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by emilianodellacasa** [comment]
@ypshenychka Confirmed

**Comment by ypshenychka** [comment]
@emilianodellacasa thanks

**Comment by ypshenychka** [comment]
@DronMDF Still missing link to original issue in PR's description and no addressee [here](https://github.com/zold-io/zold-score/pull/3#discussion_r231279249). Please correct and notify me.

**Comment by DronMDF** [comment]
@ypshenychka Done.

**Comment by ypshenychka** [comment]
@DronMDF Thanks, but still missing addressee [here](https://github.com/zold-io/zold-score/pull/3#discussion_r231279249).

**Comment by ypshenychka** [comment]
@DronMDF I don't have choice :) Thanks!

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
