### PR TITLE
#12: Interrupt busy thread

### PR DESCRIPTION
**Pull request by DronMDF**
For fix issue #12 

@yegor256 Before this patch I not shure about effective multicore calculation.
Need to check it.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#13](https://github.com/zold-io/zold-score/issues/13) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#13](https://github.com/zold-io/zold-score/issues/13) is assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/ae20fbf7-e748-4ab4-a8c1-f97894236a04); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
@DronMDF I cannot see major issues on this commit, @yegor256 we can merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@DronMDF thanks a lot!

**Comment by DronMDF** [comment]
@yegor256 You're welcome.

I thisk about 0crat...
I do not want to join to the project, because I do not want to write in ruby.
The system is not designed for occasional participation?

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#13](https://github.com/zold-io/zold-score/issues/13) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@emilianodellacasa According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issue were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by ypshenychka** [comment]
@DronMDF According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to

Please add more details into description.

**Comment by DronMDF** [comment]
@ypshenychka I do not understand how you work.
The pull request is already closed, so I am clean. :)
These are not my problems. Thisi is project problems. Write tickets.

On the other hand, I am not a member of the project at all. I am a volunteer.
I’m not interested in getting very hard for filling up a pullrequest.

**Comment by emilianodellacasa** [comment]
@ypshenychka Confirmed

**Comment by ypshenychka** [comment]
@emilianodellacasa thanks

**Comment by ypshenychka** [comment]
@DronMDF I see you on the Team page of Zerocracy, so you should've read our Policy once got aboard. In this case it's really not your problem, I agree. And not a problem of PR reviewer, since he won't be paid here anyways so he's not blocked by your ignore to my requests. However there might be a case in future, when person will simply wait 5 days for me to give a QA verdict until he gets paid if you don't make appropriate changes. 
 
So it's more about politeness than rules. It can return to you as boomerang in case some time in future you will be ticket's performer and will wait for your payment that long.

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by DronMDF** [comment]
@ypshenychka Thanks for the detailed answer.
I would be happy to accept comments until the request has not yet been included - it would be right.
Now it looks like a useless bureaucracy.

[§7](http://www.zerocracy.com/policy.html#7) A job is completed when its ticket is closed.

**Comment by ypshenychka** [comment]
@DronMDF Well, it's prerogative of ticket performer to make sure each participant in a ticket follows QA rules. He can ask for corrections before the ticket is closed, so when it comes to QA verdict I could evaluate it as 'good' and performer receives bonus. 
So in some way this '5 days rule' forces ticket performers to track their ticket's quality prior it comes to QA. 
And it's up to you - to make corrections when QA asks, or leave a person to receive payment a bit later. But to my mind it requires less efforts, than writing a long dispute comment :) 

You're welcome to submit a ticket if you see any ways how this process can be improved. This will be highly appreciated.

**Comment by DronMDF** [comment]
@ypshenychka It seems to me that this is not a quality wall. Too late. Then what is it? and for what?
If you can make comments on a closed request, then you can make comments on the quality of the code?

It seems to me that this is contrary to the principles of a zerocracy.
https://www.yegor256.com/2014/04/13/no-obligations-principle.html

@yegor256 What do you think about this?
I admit that the code got into the master without going through all the checks. 
This is not entirely correct, and someone must be punished. Let's punish the reviewer. :)

**Comment by ypshenychka** [comment]
@DronMDF I'm not reviewing code here - we have REV role for that. Adhering to QA rules at most gives us better documentation and cleaner tickets.

And reviewer is punished hear indeed - he didn't find any issues thus was not paid.

**Comment by DronMDF** [comment]
@emilianodellacasa About the punishment of the reviewer is a joke. :)

@ypshenychka Studying the zerocracy, I assumed that both the reviewer and the QA should allow the passage of changes to the master. Any comments after the change has been merged (be it typos in the request, or problems in production) - this is a project problem. There can be no comments after the work is recognized as completed.

**Comment by emilianodellacasa** [comment]
@DronMDF I am not angry at all, I was sincerely thanking @ypshenychka because I didn't know that. No hard feelings here on Zerocracy! :-)

**Comment by ypshenychka** [comment]
@DronMDF That's how the process is established. QA review comes only after work is done and decision about payment is made there. As I mentioned previously - if you see any improvements to the process, feel free to submit ticket and we'll discuss it there.

**Comment by ypshenychka** [comment]
@emilianodellacasa Sure, you can. Why not? :) It's your ticket - so you if you see any inconsistencies with QA rules, ask author to make appropriate corrections prior to merge. Thus when it comes to QA review there'll be more chances to gain bonus.

**Comment by DronMDF** [comment]
@ypshenychka I read policy...
I understood my mistakes, I promise not to do them in the future. As required in the policy.
But it is strange that the quality comes so late. At this stage, the QA can no longer affect anything. I think.

**Pull request merged**
